export default {
  id: '706582',
  name: 'Γύρος χοιρινός',
  price: 4,
  comments: '',
  large_description: null,
  start_price: 0,
  isOutOfStock: false,
  images: [],
  minQuantity: 0,
  maxQuantity: 0,
  category: {
    id: '75052',
    name: 'Αραβική πίτα',
  },
  variants: [],
  ingredient_categories: [
    {
      id: 148059,
      name: 'υλικά',
      comments: '',
      min: 0,
      max: 10,
      ingredients: [
        {
          id: 1326741,
          name: 'πατάτες τηγανητές',
          default: 0,
          max: 1,
          price: [0],
          selected: false,
        },
        {
          id: 1326735,
          name: 'ντομάτα',
          default: 1,
          max: 1,
          price: [0],
          selected: true,
        },
        {
          id: 1326734,
          name: 'ρόκα',
          default: 1,
          max: 1,
          price: [0],
          selected: true,
        },
        {
          id: 1326736,
          name: 'αγγουράκι',
          default: 1,
          max: 1,
          price: [0],
          selected: true,
        },
        {
          id: 1326737,
          name: 'σως γιαουρτιού',
          default: 1,
          max: 1,
          price: [0],
          selected: true,
        },
        {
          id: 1326738,
          name: 'ελαιόλαδο',
          default: 1,
          max: 1,
          price: [0],
          selected: true,
        },
      ],
    },
  ],
  cart_index: '0',
  quantity: 1,
};
